MovieDatabase/Models/Director.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieDatabase.Models
{
    public class Director
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime DateOfBirth { get; set; }
    }
}

MovieDatabase/ViewModels/DirectorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using MovieDatabase.Models;

namespace MovieDatabase.ViewModels
{
    public class DirectorViewModel
    {
        public int? DirectorId { get; set; }
        public string Name { get; set; }

        [Display(Name = "Date of birth")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime DateOfBirth { get; set; }
        public IEnumerable<Movie> DirectedMovies { get; set; }
    }
}

MovieDatabase/Controllers/DirectorController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieDatabase.Repositories;
using MovieDatabase.ViewModels;

namespace MovieDatabase.Controllers
{
    public class DirectorController : Controller
    {
        private readonly IDirectorRepository _directorRepository;

        public DirectorController(IDirectorRepository directorRepository)
        {
            _directorRepository = directorRepository;
        }

        [HttpGet]
        public IActionResult ListAll()
        {
            var model = _directorRepository.GetAllDirectors();
            return View(model);
        }

        [HttpGet]
        public IActionResult DirectorDetails(int id)
        {
            var director = _directorRepository.GetDirectorById(id);
            var movies = _directorRepository.GetDirectedMovies(id);

            var model = new DirectorViewModel()
            {
                DirectorId = director.Id,
                Name = director.Name,
                DateOfBirth = director.DateOfBirth,
                DirectedMovies = movies
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult DirectorSearch()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SearchDirector(string s)
        {
            var model = _directorRepository.GetAllDirectors().Where(a => a.Name.ToLower().Contains(s.ToLower()));
            return View("DirectorSearch", model);
        }

        [HttpGet]
        public IActionResult EditDirector(int id, int? errorId)
        {
            var director = _directorRepository.GetDirectorById(id);

            var model = new DirectorViewModel()
            {
                DirectorId = id,
                DateOfBirth = director.DateOfBirth,
                Name = director.Name
            };
            if (errorId == 1)
            {
                ViewBag.ErrorMessage = "Can't remove a director that is in an existing movie.";
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult EditDirector(DirectorViewModel viewModel)
        {
            var director = _directorRepository.GetDirectorById((int)viewModel.DirectorId);

            director.Name = viewModel.Name;
            director.DateOfBirth = viewModel.DateOfBirth;

            _directorRepository.UpdateDirector(director);
            _directorRepository.SaveData();

            return RedirectToAction("DirectorDetails", new { id = viewModel.DirectorId });
        }

        [HttpGet]
        public IActionResult RemoveDirector(int id)
        {
            if (!_directorRepository.IsDirectorInAnyMovie(id))
            {
                _directorRepository.RemoveDirector(id);
                _directorRepository.SaveData();
                return RedirectToAction("ListAll");
            }
            else
            {
                return RedirectToAction("EditDirector", new { id = id, errorId = 1 });
            }
        }
    }
}

MovieDatabase/Views/Director/DirectorDetails.cshtml
@model DirectorViewModel

@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

<div class="container">
    <h2>
        @Model.Name, @Model.DateOfBirth.ToString("d")
        @if (SignInManager.IsSignedIn(User))
        {
            <a class="paddingleft30" href="@Url.Action("EditDirector", new {id = Model.DirectorId})">Edit director</a>
        }
    </h2>
    <br />
    <h4 class="underline">Movies directed</h4>
    @foreach (var movie in Model.DirectedMovies)
    {
        <span>@movie.Title, @movie.ProductionYear</span>
    }
</div>

MovieDatabase/Views/Director/DirectorSearch.cshtml
@model IEnumerable<Director>


<div class="paddingcenterize">
    <h3 class="marginbottom25">Search director</h3>
    <form role="search">
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Director name" name="s">
        </div>
        <button type="submit" class="btn btn-default" asp-controller="Director" asp-action="SearchDirector">Find</button>
    </form>



    @if (Model != null)
    {
        <h2 class="margintop25">Found the following directors</h2>
        <div class="container movielistbox">
            @foreach (var director in Model)
            {
                <a href="@Url.Action("DirectorDetails", new { id = director.Id })"><h4>@director.Name</h4></a>
            }
        </div>
    }
</div>

MovieDatabase/Views/Director/EditDirector.cshtml
@model DirectorViewModel

@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <h3><span>@ViewBag.ErrorMessage</span></h3>
    <div class ="row">
    <h3 class="col-md-3">Edit director</h3>
    <h3><a data-toggle="confirmation" href="@Url.Action("RemoveDirector", new { id = Model.DirectorId })">Remove</a></h3>
    </div>
    <div class="margintop25 form-group">
        @using (Html.BeginForm("EditDirector", "Director"))
        {
            <div>@Html.ValidationSummary()</div>
            <div>
                @Html.HiddenFor(m => m.DirectorId)
                <table>
                    <tr>
                        <td>@Html.LabelFor(m => m.Name)</td>
                        <td>@Html.EditorFor(m => m.Name, new {htmlAttributes = new {@class = "form-control form-group"}})</td>
                    </tr>
                    <tr>
                        <td>@Html.LabelFor(m => m.DateOfBirth)</td>
                        <td>@Html.EditorFor(m => m.DateOfBirth, new {htmlAttributes = new {@class = "form-control form-group"}})</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Save" class="btn btn-default marginbottom25"/></td>
                    </tr>
                </table>

            </div>
        }
    </div>
}
else
{
    <h2>Sorry, this page is for admins only.</h2>
}

MovieDatabase/Views/Director/ListAll.cshtml
@model IEnumerable<Director>

<div class="margintop25">
    @foreach (var director in Model)
    {
        <a href="@Url.Action("DirectorDetails", new { id = director.Id })"><h4>@director.Name</h4></a>
    }
</div>