MovieDatabase/Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieDatabase.Repositories;
using MovieDatabase.ViewModels;

namespace MovieDatabase.Controllers
{
    public class ActorController : Controller
    {
        private readonly IActorRepository _actorRepository;

        public ActorController(IActorRepository actorRepository, IMovieRepository movieRepository)
        {
            _actorRepository = actorRepository;
        }

        [HttpGet]
        public IActionResult ListAll()
        {
            var model = _actorRepository.GetAllActors();
            return View(model);
        }

        [HttpGet]
        public IActionResult ActorDetails(int id)
        {
            var actor = _actorRepository.GetActorById(id);
            var movies = _actorRepository.GetMoviesForActor(id);

            var model = new ActorViewModel
            {
                ActorId = actor.Id,
                Name = actor.Name,
                DateOfBirth = actor.DateOfBirth,
                Movies = movies
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult ActorSearch()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SearchActor(string s)
        {
            var model = _actorRepository.GetAllActors().Where(a => a.Name.ToLower().Contains(s.ToLower()));
            return View("ActorSearch", model);
        }

        [HttpGet]
        public IActionResult EditActor(int id, int? errorId)
        {
            var actor = _actorRepository.GetActorById(id);
            var model = new ActorViewModel
            {
                ActorId = id,
                DateOfBirth = actor.DateOfBirth,
                Name = actor.Name
            };
            if (errorId == 1)
            {
                ViewBag.ErrorMessage = "Can't remove an actor that is in an existing movie.";
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult EditActor(ActorViewModel viewModel)
        {
            var actor = _actorRepository.GetActorById((int)viewModel.ActorId);

            actor.Name = viewModel.Name;
            actor.DateOfBirth = viewModel.DateOfBirth;

            _actorRepository.UpdateActor(actor);
            _actorRepository.SaveData();

            return RedirectToAction("ActorDetails", new {id = viewModel.ActorId});
        }

        [HttpGet]
        public IActionResult RemoveActor(int id)
        {
            if (!_actorRepository.IsActorInAnyMovie(id))
            {
                _actorRepository.RemoveActor(id);
                _actorRepository.SaveData();
                return RedirectToAction("ListAll");
            }
            else
            {
                return RedirectToAction("EditActor", new { id = id, errorId = 1 });
            }
        }
    }
}

MovieDatabase/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieDatabase.Models;
using MovieDatabase.Repositories;
using MovieDatabase.ViewModels;

namespace MovieDatabase.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepository;
        private readonly IActorRepository _actorRepository;

        public MovieController(IMovieRepository movieRepository,
            IActorRepository actorRepository)
        {
            _movieRepository = movieRepository;
            _actorRepository = actorRepository;
        }


        public IActionResult SearchMovie(string s)
        {
            if (String.IsNullOrEmpty(s))
            {
                return RedirectToAction("Index", "Home");
            }
            var movies = _movieRepository.GetAllMovies().Where(m => m.Title.ToLower().Contains(s.ToLower()));
            return View("SearchResult", movies);
        }

        [HttpGet]
        public IActionResult MovieDetails(int id)
        {
            var movie = _movieRepository.GetMovieById(id);
            var actors = new List<Actor>();
            foreach (var movieActor in movie.MovieActors)
            {
                actors.Add(movieActor.Actor);
            }
            var model = new MovieViewModel
            {
                Director = movie.Director,
                ProductionYear = movie.ProductionYear,
                Title = movie.Title,
                Actors = actors,
                Ratings = movie.Ratings.ToList(),
                AverageScore = movie.AverageScore,
                Genres = movie.Genres,
                MovieId = movie.Id
            };
            return View(model);
        }

        [HttpGet]
        public IActionResult AddMovie()
        {
            var model = new AddMovieViewModel();
            model.DirectorDoB = null;
            model.ProductionYear = null;
            return View(model);
        }

        [HttpPost]
        public IActionResult AddMovie(AddMovieViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var movie = new Movie
                {
                    Director = new Director
                    {
                        DateOfBirth = Convert.ToDateTime(viewModel.DirectorDoB),
                        Name = viewModel.DirectorName
                    },
                    Title = viewModel.Title,
                    ProductionYear = Convert.ToInt32(viewModel.ProductionYear)
                };
                var genre = _movieRepository.CheckDbIfGenreExists(new Genre {GenreName = viewModel.SelectedGenre});
                movie.Genres.Add(genre);
                _movieRepository.AddMovie(movie);
                _movieRepository.SaveData();
                return RedirectToAction("MovieDetails", new {id = movie.Id});
            }
            var model = new AddMovieViewModel();
            return View(model);
        }

        [HttpGet]
        public IActionResult AddActors(int? id)
        {
            var model = new AddActorViewModel();
            model.ActorDateOfBirth = null;
            foreach (var movie in _movieRepository.GetAllMovies())
            {
                model.Movies.Add(new SelectListItem() {Text = movie.Title, Value = movie.Id.ToString()});
            }
            if (id != null)
            {
                model.SelectedMovieId = (int)id;
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult AddActors(AddActorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var dbMovie = _movieRepository.GetMovieById(model.SelectedMovieId);
                var actor = new Actor
                {
                    Name = model.ActorName,
                    DateOfBirth = Convert.ToDateTime(model.ActorDateOfBirth)
                };

                _actorRepository.AddActorToMovie(actor, dbMovie);
                _movieRepository.SaveData();

                foreach (var movie in _movieRepository.GetAllMovies())
                {
                    model.Movies.Add(new SelectListItem() {Text = movie.Title, Value = movie.Id.ToString()});
                }
                return RedirectToAction("AddActors");
            }
            return RedirectToAction("AddActors");
        }

        [HttpGet]
        public IActionResult DeleteMovie()
        {
            var model = new DeleteMovieViewModel();

            foreach (var movie in _movieRepository.GetAllMovies())
            {
                model.Movies.Add(new SelectListItem() {Text = movie.Title, Value = movie.Id.ToString()});
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult DeleteMovie(DeleteMovieViewModel viewModel)
        {
            if (viewModel.SelectedMovieId != 0)
            {
                _movieRepository.DeleteMovie(viewModel.SelectedMovieId);
                _movieRepository.SaveData();
            }


            var model = new DeleteMovieViewModel();
            foreach (var movie in _movieRepository.GetAllMovies())
            {
                model.Movies.Add(new SelectListItem() {Text = movie.Title, Value = movie.Id.ToString()});
            }
            return RedirectToAction("DeleteMovie", model);
        }

        [HttpGet]
        public IActionResult ListAll()
        {
            var model = _movieRepository.GetAllMovies();

            return View(model);
        }

        [HttpGet]
        public IActionResult AddRating(int? id)
        {
            var model = new AddRatingViewModel();

            foreach (var movie in _movieRepository.GetAllMovies())
            {
                model.Movies.Add(new SelectListItem() {Text = movie.Title, Value = movie.Id.ToString()});
            }
            if (id != null)
            {
                model.SelectedMovieId = (int) id;
            }
            return View(model);
        }

        public IActionResult AddRating()
        {
            var model = new AddRatingViewModel();

            foreach (var movie in _movieRepository.GetAllMovies())
            {
                model.Movies.Add(new SelectListItem() {Text = movie.Title, Value = movie.Id.ToString()});
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult AddRating(AddRatingViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var rating = new Rating
                {
                    Review = viewModel.ReviewText,
                    ReviewDate = DateTime.Now,
                    ReviewerName = viewModel.ReviewerName,
                    Score = viewModel.Score
                };
                _movieRepository.AddRating(rating, viewModel.SelectedMovieId);
                _movieRepository.SaveData();
            }
            return RedirectToAction("MovieDetails", new {id = viewModel.SelectedMovieId});
        }

        [HttpGet]
        public IActionResult TopList()
        {
            var model = _movieRepository.GetTopListMovies();
            return View(model);
        }

        [HttpGet]
        public IActionResult AddGenre(int? id)
        {
            var model = new AddGenreViewModel();

            foreach (var movie in _movieRepository.GetAllMovies())
            {
                model.Movies.Add(new SelectListItem() {Text = movie.Title, Value = movie.Id.ToString()});
            }
            if (id != null)
            {
                model.SelectedMovieId = (int)id;
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult AddGenre(AddGenreViewModel viewModel)
        {
            _movieRepository.AddGenre(new Genre {GenreName = viewModel.SelectedGenre}, viewModel.SelectedMovieId);
            _movieRepository.SaveData();
            return RedirectToAction("MovieDetails", new {id = viewModel.SelectedMovieId});
        }

        [HttpGet]
        public IActionResult EditMovie(int id)
        {
            var movie = _movieRepository.GetMovieById(id);
            var actors = new List<Actor>();
            foreach (var movieActor in movie.MovieActors)
            {
                actors.Add(movieActor.Actor);
            }
            var model = new EditMovieViewModel
            {
                Actors = actors,
                Ratings = movie.Ratings,
                MovieId = movie.Id,
                ProductionYear = movie.ProductionYear,
                Title = movie.Title,
                Genres = movie.Genres
            };

            return View(model);
        }

        [HttpPost]
        public void EditTitleAndProductionYear(string movieTitle, int movieProductionYear, int movieId)
        {
            var movie = _movieRepository.GetMovieById(movieId);
            movie.Title = movieTitle;
            movie.ProductionYear = movieProductionYear;

            _movieRepository.UpdateMovie(movie);
            _movieRepository.SaveData();
        }

        [HttpPost]
        public void RemoveActor(int movieId, int actorId)
        {
            var movie = _movieRepository.GetMovieById(movieId);
            var actor = movie.MovieActors.FirstOrDefault(ma => ma.ActorId == actorId && ma.MovieId == movieId);
            if (actor != null)
            {
                movie.MovieActors.Remove(actor);
                _movieRepository.UpdateMovie(movie);
                _movieRepository.SaveData();
            }
        }

        [HttpPost]
        public void RemoveRating(int movieId, int ratingId)
        {
            _movieRepository.RemoveRatingFromMovie(ratingId, movieId);
            _movieRepository.SaveData();
        }

        [HttpPost]
        public void RemoveGenre(int movieId, int genreId)
        {

MovieDatabase/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MovieDatabase</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/css/site.css" type="text/css"/>
    <script src="~/lib/jquery/dist/jquery.js"></script>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
        <script src="~/lib/jquery/dist/jquery.js"></script>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/css/site.css" type="text/css"/>
        <script src="~/lib/jquery/dist/jquery.js"></script>
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">

    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a asp-area="" asp-controller="Home" asp-action="Index">
            <img src="~/images/logo.png" id="smallLogo" class="img-responsive center-block"/>
        </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            @await Html.PartialAsync("_MoviesPartial")
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="~/images/actor.png" width="20" height="20"/> Actors <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li>
                        <a asp-controller="Actor" asp-action="ActorSearch">Search actor</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a asp-controller="Actor" asp-action="ListAll">List all actors</a>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="~/images/director.png" width="20" height="20"/> Directors <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li>
                        <a asp-controller="Director" asp-action="DirectorSearch">Search director</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a asp-controller="Director" asp-action="ListAll">List all directors</a>
                    </li>
                </ul>

            </li>

            <li>
                <a asp-controller="Movie" asp-action="TopList"><img src="~/images/list.png" width="20" height="20"/> Top movies</a>
            </li>
        </ul>

        <div class="col-sm-3 col-md-3">
            <form class="navbar-form" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search movie" name="s">
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-default" asp-controller="Movie" asp-action="SearchMovie">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>

        <ul class="nav navbar-nav navbar-right paddingright30">
            <li id="temperature"></li>
            <li class="marginleft10">@await Html.PartialAsync("_LoginPartial")</li>
        </ul>
    </div>
</nav>

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; 2017 - Tacos</p>
    </footer>
</div>

<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/bootstrap-confirmation.min.js"></script>
    <script src="~/js/weatherapi.js"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/bootstrap-confirmation.min.js"></script>
    <script src="~/js/weatherapi.js"></script>
</environment>

@RenderSection("Scripts", required: false)
<script src="~/js/site.js"></script>
<script src="~/js/weatherapi.js"></script>
</body>
</html>

MovieDatabase/Views/Shared/_MoviesPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="~/images/movie.png" width="20" height="20"/> Movies <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a asp-controller="Movie" asp-action="AddMovie">Add movie</a></li>
            <li><a asp-controller="Movie" asp-action="AddActors">Add actors</a></li>
            <li><a asp-controller="Movie" asp-action="AddRating">Rate movie</a></li>
            <li><a asp-controller="Movie" asp-action="AddGenre">Add genre to movie</a></li>
            <li><a asp-controller="Movie" asp-action="DeleteMovie">Delete movie</a></li>
            <li class="divider"></li>
            <li><a asp-controller="Movie" asp-action="ListAll">List all movies</a></li>
        </ul>
    </li>
}
else
{
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="~/images/movie.png" width="20" height="20"/> Movies <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a asp-controller="Movie" asp-action="AddRating">Rate movie</a></li>
            <li class="divider"></li>
            <li><a asp-controller="Movie" asp-action="ListAll">List all movies</a></li>
        </ul>
    </li>
}